name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  phpunit:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: PHP test
      uses: descom-es/php8-test@master
